version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    assignees:
      - "beevelop"
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    assignees:
      - "beevelop"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      docker:
        patterns:
          - "*"
