sudo: required

services:
  - docker

script:
  - docker build -t lovadroid .
  - docker run -d lovadroid
  - docker ps -a
  - docker run lovadroid /bin/sh -c "sdkmanager --list && mvn -v && gradle -v && java -version && ant -version"
