sudo: required

services:
  - docker

script:
  - npm i -g npm
  - npm install dockerlint
  - dockerlint Dockerfile
  - docker build -t local/android .
  - docker run -d local/android
  - docker ps -a
  - docker run local/android /bin/sh -c "sdkmanager --list && mvn -v && gradle -v && java -version && ant -version"
