sudo: required

services:
  - docker

script:
  - docker build -t beendroid .
  - docker run -d beendroid
  - docker ps -a
  - docker run beendroid /bin/sh -c "sdkmanager --list && mvn -v && gradle -v && java -version && ant -version"
